<a href="https://colab.research.google.com/github/Akil27/Akil27/blob/CSE111/20201041_Akil_Rahman_Efad_LabAssignment06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#AnsToQuestionNo01

class Student():
    ID=0
    def __init__(self,name,dept,age,cgpa):
        self.name=name
        self.dept=dept
        self.age=age
        self.cgpa=cgpa
        Student.ID+=1


    def get_details(self):
        print("ID:",self.ID)
        print("Name:",self.name)
        print("Department:",self.dept)
        print("Age:",self.age)
        print("CGPA:",self.cgpa)

    @classmethod
    def from_String(cls,info):
        name,dept,age,cgpa=info.split("-")
        obj=cls(name,dept,age,cgpa)
        return obj


s1 = Student("Samin", "CSE", 21, 3.91)
s1.get_details()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.get_details()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.get_details()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.get_details()

print("=======================")
print("Subtask5= Class variable are universal variable for every object created under that class while instance variable are unique for each object created under that particular class.")
print("Subtask6= Class methods are can only manipulate class behaviour while instance methods can only manipulate object behaviour.")

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96
=======================
Subtask5= Class variable are universal variable for every object created under that class while instance variable are unique for each object created under that particular class.
Subtask6= Class methods are can only manipulate class behaviour while instance methods can only manipulate object behaviour.

In [ ]:
#AnsToQuestionNo02

class Assassin():
    num_assassin=0
    def __init__(self,name,s_rate):
        self.name=name
        self.s_rate=s_rate
        Assassin.num_assassin+=1

    def printDetails(self):
        print("Name:",self.name)
        print("Success rate:",self.s_rate)
        print("Total number of Assassin:",Assassin.num_assassin)

    @classmethod
    def failureRate(cls,name,f_rate):
        obj=cls(name,100-f_rate)
        return obj

    @classmethod
    def failurePercentage(cls,name,f_percentage):
        obj=cls(name,100-f_percentage)
        return obj


john_wick = Assassin('John Wick', 100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage('Akabane', 10)
akabane.printDetails()

Name: John Wick
Success rate: 100
Total number of Assassin: 1
================================
Name: Nagisa
Success rate: 80
Total number of Assassin: 2
================================
Name: Akabane
Success rate: 90
Total number of Assassin: 3

In [ ]:
#AnsToQuestionNo03

class Passenger():
    count=0

    def __init__(self,name):
        self.name=name
        Passenger.count+=1

    def set_bag_weight(self,weight):
        self.weight=weight


    def printDetail(self):
        print("Name:",self.name)
        if self.weight <= 20:
            print("Bus Fare:",450)
        elif self.weight > 20 and self.weight <= 50:
            print("Bus Fare:",500)
        else:
            print("Bus Fare:",550)

        

print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus Fare: 550
=========================
Name: Carol
Bus Fare: 450
=========================
Name: Mike
Bus Fare: 500
=========================
Total Passenger: 3

In [ ]:
#AnsToQuestionNo04

class Travel():
    count=0

    def __init__(self,source,destination):
        self.source=source
        self.destination=destination
        self.time=1
        Travel.count+=1

    def set_time(self,time):
        self.time=time

    def set_destination(self,destination):
        self.destination=destination

    def set_source(self,source):
        self.source=source

    def display_travel_info(self):
        obj="Source:"+str(self.source)+"\nDestination:"+str(self.destination)+"\nFlight Time"+str(self.time)+":00"
        return obj


print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =", Travel.count)

No. of Traveller = 0
=======================
Source:Dhaka
Destination:India
Flight Time1:00
=======================
Source:Kuala Lampur
Destination:Dhaka
Flight Time23:00
=======================
Source:Dhaka
Destination:Germany
Flight Time15:00
=======================
Source:Malaysia
Destination:Canada
Flight Time9:00
=======================
No. of Traveller = 4

In [ ]:
#AnsToQuestionNo05

class Employee():
    def __init__(self,name,workingPeriod):
        self.name=name
        self.workingPeriod=workingPeriod

    @classmethod
    def employeeByJoiningYear(cls,name,year):
        obj=cls(name,year)
        return obj

    @staticmethod
    def experienceCheck(workingPeriod,gender):
        if workingPeriod > 3 and gender=="male":
            return "He is experienced"
        elif workingPeriod > 3 and gender=="female":
            return "She is experienced"
        elif workingPeriod < 3 and gender=="male":
            return "He is not experienced"
        elif workingPeriod < 3 and gender=="female":
            return "She is not experienced"


employee1 = Employee('Dororo', 3)
employee2 = Employee.employeeByJoiningYear('Harry', 2016)
print(employee1.workingPeriod)
print(employee2.workingPeriod)
print(employee1.name)
print(employee2.name)
print(Employee.experienceCheck(2, "male"))
print(Employee.experienceCheck(3, "female"))

3
2016
Dororo
Harry
He is not experienced
None

In [ ]:
#AnsToQuestionNo06

class Laptop():
    laptopCount=0

    def __init__(self,name,count):
        self.name=name
        self.count=count
        Laptop.laptopCount+=1

    @staticmethod
    def advantage():
        print("Laptops are portable")

    @staticmethod
    def resetCount():
        Laptop.laptopCount=0


lenovo = Laptop("Lenovo", 5);
dell = Laptop("Dell", 7);
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

Lenovo 5
Dell 7
Total number of Laptops 2
Laptops are portable
Total number of Laptops 0

In [ ]:
#AnsToQuestionNo07

class Cat():
    Number_of_cats=0
    def __init__(self, color, work):
        self.__color=color
        self.__work=work
        Cat.Number_of_cats+=1
 
    def changeColor(self, color):
        self.__color=color
 
    def printCat(self):
        print(f"{self.__color} cat is {self.__work}")
 
    @classmethod
    def no_parameter(cls):
        color="White"
        work="sitting"
        obj=Cat(color, work)
        return obj
 
    @classmethod
    def first_parameter(cls, color):
        work="sitting"
        obj=Cat(color, work)
        return obj
 
    @classmethod
    def second_parameter(cls, work):
        color="Grey"
        obj=Cat(color, work)
        return obj


print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

Total number of cats: 0
=======================
White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Grey cat is playing
Blue cat is sitting
Purple cat is jumping
=======================
Total number of cats: 5

In [ ]:
#AnsToQuestionNo08
import math
class Cylinder():
    radius=5
    height=18
    
    def __init__(self,radius,height):
        self.radius=radius
        self.height=height
        print("Default radius:",Cylinder.radius,"and height:",Cylinder.height)
        Cylinder.radius=self.radius
        Cylinder.height=self.height
        print("Updated radius:",Cylinder.radius,"and height:",Cylinder.height)


    @classmethod
    def swap(cls,height,radius):
        obj=Cylinder(radius,height)
        return obj

    @classmethod
    def changeFormat(cls,info):
        radius,height=info.split("-")
        obj=Cylinder(int(radius),int(height))
        return obj

    @staticmethod
    def area(radius,height):
        area=(2*math.pi*(Cylinder.radius**2)+2*math.pi*Cylinder.radius*Cylinder.height)
        print("Area:",area)

    @staticmethod
    def volume(radius,height):
        volume=(math.pi*(Cylinder.radius**2)*Cylinder.height)
        print("Volume:",volume)


c1 = Cylinder(0,0)
Cylinder.area(c1.radius,c1.height)
Cylinder.volume(c1.radius,c1.height)
print("===============================")
c2 = Cylinder.swap(8,3)
c2.area(c2.radius,c2.height)
c2.volume(c2.radius,c2.height)
print("===============================")
c3 = Cylinder.changeFormat("7-13")
c3.area(c3.radius,c3.height)
c3.volume(c3.radius,c3.height)
print("===============================")
Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)
print("===============================")
Cylinder(3,5).volume(Cylinder.radius,Cylinder.height)

Default radius: 5 and height: 18
Updated radius: 0 and height: 0
Area: 0.0
Volume: 0.0
===============================
Default radius: 0 and height: 0
Updated radius: 3 and height: 8
Area: 207.34511513692635
Volume: 226.1946710584651
===============================
Default radius: 3 and height: 8
Updated radius: 7 and height: 13
Area: 879.645943005142
Volume: 2001.1945203366981
===============================
Default radius: 7 and height: 13
Updated radius: 0.3 and height: 5.56
Area: 11.045839770021713
===============================
Default radius: 0.3 and height: 5.56
Updated radius: 3 and height: 5
Volume: 141.3716694115407

In [ ]:
#AnsToQuestionNo09

class Student():
    total_students=0
    bracu_students=0
    rest_of_the_students=0
    def __init__(self,name,department,institute="BRAC University"):
        self.name=name
        self.department=department
        self.institute=institute
        Student.total_students+=1
        if self.institute =="BRAC University":
            Student.bracu_students+=1
        else:
            Student.rest_of_the_students+=1

    def individualDetail(self):
        print("Name:",self.name)
        print("Department:",self.department)
        print("Institution:",self.institute)
 
    @classmethod
    def printDetails(cls):
        print("Total Students(s):",Student.total_students)
        print("BRAC University Student(s):",Student.bracu_students)
        print("Other Institution Student(s):",Student.rest_of_the_students)
 
    @classmethod
    def createStudent(cls,name,department,institute="BRAC University"):
        return cls(name,department,institute)


Student.printDetails()
print('#########################')
mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()
print('========================')
harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()
print('=========================')
levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Students(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution: BRAC University
------------------------------------------
Total Students(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Students(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department: CSE
Institution: BRAC University
--------------------------------------------
Total Students(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1

In [ ]:
#AnsToQuestionNo10

class SultansDine:
    total_sell=0
    total_branch=0
    listt=[]
 
    def __init__(self,place):
        self.place=place
        self.quantity=0
        SultansDine.total_branch+=1
        SultansDine.listt.append([self.place])
 
    def sellQuantity(self,quantity):
        self.quantity=quantity
 
    def branchInformation(self):
        Branch_sell=0
        if self.quantity<10:
            Branch_sell=self.quantity*300
        elif self.quantity<20:
            Branch_sell=self.quantity*350
        else:
            Branch_sell=self.quantity*400
        SultansDine.total_sell+=Branch_sell
        SultansDine.listt[SultansDine.total_branch-1]+=[Branch_sell]
        print(f"Branch Name: {self.place}")
        print(f"Branch Sell: {Branch_sell} Taka")
 
    @classmethod
    def details(cls):
        print(f"Total Number of branch(s): {SultansDine.total_branch}")
        print(f"Total Sell: {SultansDine.total_sell} Taka")
        for i,j in cls.listt:
            print(f"Branch Name: {i}, Branch Sell: {j} Taka")
            sell_per="{:.2f}".format((j/SultansDine.total_sell)*100)
            print(f"Branch consists of total sell's: {sell_per}%")


SultansDine.details()
print('########################')
dhanmodi = SultansDine('Dhanmondi')
dhanmodi.sellQuantity(25)
dhanmodi.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 10000 Taka
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 100.00%
========================
Branch Name: Baily Road
Branch Sell: 5250 Taka
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 65.57%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700 Taka
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 55.71%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 29.25%
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch consists of total sell's: 15.04%